@auth = Authorization: Bearer {{private_key}}
@index = experience

### List keys
GET {{base_url}}/keys
Accept: application/json
Authorization: Bearer {{master_key}}

### List indexes
GET {{base_url}}/indexes
Accept: application/json
{{auth}}

### Create an index
POST {{base_url}}/indexes
Accept: application/json
Content-Type: application/json
{{auth}}

{
  "uid": "{{index}}",
  "primaryKey": "id"
}
 
### Delete an index
DELETE {{base_url}}/indexes/{{index}}
Accept: application/json
{{auth}}

### Filterable attributes
GET {{base_url}}/indexes/{{index}}/settings/filterable-attributes
Accept: application/json
{{auth}}

### sortable attributes
GET {{base_url}}/indexes/{{index}}/settings/sortable-attributes
Accept: application/json
{{auth}}

### 
### 
### Update attributes
POST {{base_url}}/indexes/destination/settings
Content-Type: application/json
Accept: application/json
{{auth}}

{
  "filterableAttributes": [
    "type1", "type2", "type3",
    "country"
  ],
  "sortableAttributes": ["name", "published_at"]
}

### Update attributes
POST {{base_url}}/indexes/experience/settings
Content-Type: application/json
Accept: application/json
{{auth}}

{
  "filterableAttributes": [
    "type1", "type2", "type3",
    "country"
  ],
  "sortableAttributes": ["name", "published_at"]
}

### Update advisor attributes
POST {{base_url}}/indexes/advisor/settings
Content-Type: application/json
Accept: application/json
{{auth}}

{
  "filterableAttributes": [
    "experienceType1", "experienceType2", "experienceType3",
    "destinationType1", "destinationType2", "destinationType3",
    "type1", "type2", "type3",
    "language1", "language2", "language3",
    "country"
  ],
  "sortableAttributes": ["name"]
}

###
###
### Search: query
POST {{base_url}}/indexes/{{index}}/search
Accept: application/json
Content-Type: application/json
{{auth}}

{
  "q": "priv",
  "offset": 0
}

### Search: filter by type
POST {{base_url}}/indexes/{{index}}/search
Accept: application/json
Content-Type: application/json
{{auth}}

{
  "offset": 0
}
