<script lang="ts">
  import BlurhashImage from '$lib/components/svelte-blurhash/BlurhashImage.svelte';
  import Blurhash from './svelte-blurhash/Blurhash.svelte';

  export let url = '';
  export let blurHash = '';
  export let alternativeText: string | undefined = undefined;
  export let caption: string | undefined = undefined;
  export let name: string | undefined = undefined;
  export let alt: string | undefined = undefined;
  export let fadeDuration: number = 1000;
  const hashes = [
    'UCIzb.]i0q0z00Ey?XMz0Jo%R5~Uss9tXT-n',
    'UGHBh@?wx[DhxFM|t6M{J5M{?Fxu4ojD-pxt',
    'UAHxKJ00%Px^00?vD%RP0oRPD$ofMwIU~ptR',
    'U9Ex;UIo03={w]Si%h?G0L%2|q0e5SRO^jo}',
    'UGH1*-tj.6_3~AK5t7t6GGI[H@VYyDR5RQo}',
    'U6C=*c~9RPxHEfR+tQI:01jv={aK~VWBNZtR',
    'UOH^|s9[0K%L_M$iD*xu%faexuWCnQJ7xuaK',
    'UQEpKSTO8_sk-oRjWCt8p0R+V=xaIrogocjY',
    'U18r]7X54;x@Efoe%1WB9bof-oRk~TV[9bt6',
    'UIELEIxa0LRj~BxaWna{0fof~B%1EKkB%2xa',
    'UIH.KK.AQk:ztmt7IT-P?ZDiM{x^%2E2%ht9',
    'UPINy}$*?vxt4nM_n~Rj_N-;RjozMxRPs:ae',
    'UiM@$F}VJQxa$%S2bHjca|azjaWUofjtfkaz',
    'UCE-,Noz0K~A%MxsM_NH0g={^j57R$ogxvNG',
    'UaFr@fE1M|ax%hM{M|ax_4M{ofoetmM|jroI',
    'UiIY8|ofkDof_4j[ofazWYayRiayt7j[ayj[',
    'U1Eo0o0000Oa00^%~U~80257~V0f^h%20fJC',
    'UFD9;l-oIot700iv-oRj?w%1t6of-nkCRPjs',
    'UtF%iWfnkCRjKUR.ocWCx_V?axof9GjEj]of',
    'UODAl.D%RPoz~Rf,Rjofp1%2bIae%$jFoeRj',
    'URBzLlMwITtSHXXnx]ngt:Rlnhs+wajqoHt8',
    'UZGI};RhWBj[00%1s:oe?wbcWBazoeV@WBWV',
    'UmHf@uaeazW;?KIpWBV[JBaMsmW;0LR*kAWC',
    'UEI#V:0000~T-.9d=_og?v?G9G4p^*xt9aoI',
    'UQI4bJo}9^Rk8wtmtlt8.mWBenbI9ui_r?ax',
    'UXE:6onhM{ozpykCWEadyEM|t5a~IpWBkDoc',
    'UCGlO}yD+?wHBHEMsl?G00bwEMxvH=M|tSS5',
    'UBI#3@4T01?F01x]o{w]00?G~pIV9aI]4=f+',
    'U}IOw?jZR*ay.AayaykCt7bHj[ayxBjsayj[',
    'UAIER,?_s@9arrw@x^Sh*0bbQlw]MyRO%gxv',
    'U9Gmef4-3pEJ7B%MU{xb03IU?}Myud%M4Uoz',
    'UdDmXJ?wS%tSDgMcjXV?XAWYRPV@acxt%Mog',
    'UD8{Ci;eI+NYA7Jms?oO1YOGxZsl}J,oNGS2',
    'U8EL{h%%kqI]00ibRkR+0H-OM{M_BGS%%L%M',
    'UADv.hALT0o~8wZgR4oLB@pe.8MxvdZ#V@tR',
    'UQF?Ou%Na$oL00RPoLj[*0V@RjWBIVtSbIof',
    'UEE30v0I;a4-tSkXRljc0@sr$us*t6WCbJog',
    'UPCP;b_4WZRkkDkCayay4mD$t6s:RhW9oefj',
    'UsK-nDI^ogt7.Ax]R-RkS7ocs,kCR-RPoJf+',
    'UPGm7XBH*0-P?vRPs,xupdD%Mxo#DiXTNfIV',
    'UOD^N7%0xTkX8wD+NfRjyZt3xuaeZ}IAxuW?',
    'ULF$R:~q?vI9R:oIaeRO%3%Mt8oeM{M{WVa}',
    'USGkp~~pp0%gs.RkRjjYNfR,jFWAozoga#WX',
    'U3I}X~%L00s:xtj@_2Rj00ay01az00WB00oe',
    'UICuSsL}jDXB0HtltLaepfN%V?n|MK%ho$f5',
    'UlGI=SRjRjRj_4WAaeV[%NWDWBoes;t7bHof',
    'UCGSDe00^kM|YQcF%MWBLNITRjbv?wWVIAe-',
    'UOHn]K9boHV[O_E3oHayOvNLxWRkIvt8%1WC',
    'U9Dl+e%14m00_49w4nD%8|%2In9aIW?GRO9G',
    'UGI4keT|?b~p?G%LNHIV%M-:%MxvIANHenoJ',
    'UWFiiQ_Nsls+v0R3tRoggkNIRPj]MxxuogRP',
    'UpFirit7WBof_4ofWVj[RojYj[afE0axj[ay',
    'UBF$CMRO3?K40cNEHsIo7D%h+awKmj-=TKo#',
    'U=DdeXWCjZfRt:a}ayfRkDWBj[fPM_j?ayfQ',
    'UDFXxGC70f}Z-;VYIoXmE+IBv}KO%MIprqxa',
    'UNDlvI-TM{t7?GW=%1jF~AV@WVf6-SM|IpRj',
    'UmLzHgIBWVj@?^slV@WVNHbve.jFr?j[ozfk',
    'U8BWY;Ng00}jzmrp%%FhD$%N%NMxyDx]VYj=',
    'U8E.b1D+~p%g_39F$%s.0-t5jFRk},E3T1X8',
    'UcFO[akCWAWV?woLoIfQ.8ofjsay%MofbIf6',
    'UyIXpl~VT0IpbHj]j@bIbIj[jsj[f6ayaya{',
    'UBICjD2zgjM:5_G0aAGG+NBB=GKeJNJ4{vV@',
    'UCFhnnys.7nhXl-o^MEM^$E3NI$%%fXAogV@',
    'UKFFBM-@v|ngTNS+InM|ESX9t6%0=?RjRPM|',
    'USEML7ayD%Rj00j[xut7_NWCNFWB9FofazbH',
    'UcE:MG-Czp-;I_I^R*V=?dxvR#X8giNMVus+',
    'UOFO[c?wW?IU00Dhj?%Mtm%gn$RjrqNGWXae',
    'UIDSzR~p0L9Z004n-:-:.7-;%2RjWBRjM{NG',
    'URF=~*~EJO8{_NyDM|RPx^tQoKWXt8oJjYW;',
    'UNDTeYthW,Z~HXImactTt:xv%NMwi_VsaKRk',
    'UbIqs7XoJFT1}fkDf+WCEVr:jDs*xVoJRlt6',
    'UGEyh}NF4mM{_4M{9ZMytS-pD*IUxuRlM{%M',
    'U8D+l2%3019H00V?NNxt01T0~UnNOtIUwGT0',
    'UGF=BZMxE+~T8{RkM|I[9Z%f%1Ip-pazozRP',
    'UMDJV8_No$xw-Tt7I]WB-U%gtnxvIUM{Riaw',
    'U8Db.tO=}*9#A2RiMy-p57%1xGxFM_S6w[IU',
    'UWHd:4~q?u?bt8t8o#o#n$f6WYbIM_M_M_RO',
    'UAEo3zIV9aD%z;M|xakW02-:WCf,_MRjM|Io',
    'U49s^.oz01Iq~U-:M|IV00-n^+RjRPITt7t8',
    'UcFPWpt8kAj[00Rjfiay?dt7j@j[Diaxf8j[',
    'UcEVpV%MR%of00IUogWB.TxujFj[D%Rjayj[',
    'UAG7xI^i}jwc^$s;xsIWK6oLIo$%t8xtIVs-',
    'UNG]j=aI%Nxu8wxtRiRiu6t8WAt7xbM|xvt7',
    'UHE{nB4nIXRQ9D-;IWV{?^IUxaRj00?an,WB',
    'UPDcQ|awIUad00og%Mog_4jYIVV@9EoNxuog',
    'U7GR;s^,R69X00AC8|T18wrp~WR:IEIp-Tbq',
    'UbD0cX_4j^RPE1NGj[j?IoM|M{WB-;xtj?ax',
    'UKEMd@%$D%Rk00M_n~of4TV=-;Rj?wR.M|of',
    'U06t^31+00eV?G~npH02}f==00m+D+IqouRQ',
    'UCEpTo00k4X5_}F%x_tUX;%gVCn3~oeRI^oI',
    'U:F?IvRjaxRj.AWBj@WCXAkDa#ofIpofj?kC',
    'UYB|~bRkIAWD8^obx]Rj*0M|jEt7R4t6RjWB',
    'UAJZoUHXTKqD00Fx#80203rVS~==_Kx_?a?b',
    'USFF?QS*I9of4TNGxuV@~qRjkCxuH=t7WERj',
    'UNFsfR%gWCj]00V[ofj@Mcngayay?wocf5az',
    'UDEyYv?[?[%zx]IoMyM{9rIoM{M{WBn+sDV]',
    'UAF=UB00L}~U-KER^,NF9H%Ln3K7ngxaIq$~',
    'UaFrq#_2oeWV~q-;RkWB_3%MWBWBx]R+RjjY',
    'USI}Lk~p-.~VEQt3RPIV_1NGD*S2?a%LaeR+',
    'UaI5b-E3XRIU~UE29FR*-=adM{xtT2s+jJWB',
    'U$F6n8WBt7t7?waeogof%ioefRa#%gofWBWV',
    'UFGIP=?a%Mn$9G9FXAob~V$i%MMx-qjDt7s.',
    'UDPjJlxu-;xu00IUofM{M{IUWBWB~qRkj[of',
    'UHFF?RpJ00tQ4TMvx_s.I{NHxtRi~q%LMxbc',
    'UeB}g~%hMcRO=;%gNLRl.AxCV=WW%itnaKoI',
    'U59GHiWW0Q$~R-j@I@R+08oL~7Ir^fazw]xY',
    'U5G*i;4T03?t00^+slVY00%4?D?W~pE1E3aP',
    'U5EK.J=_0KEN~q$yRNR+0Os9,t$%0yxZ-pxY',
    'UTHnZ.?tVY9a~otQIBn%WBIpIpxtozR+oMjb',
    'UCFy4Z1]FZnS}FJQxZr@1aRj=ekB1vaLNaS#',
    'U%E3Ywf7but6pfWEa$WWT2jvn$R+jFoyfPn$',
    'U6SPX_pI?E~X~UyD9HDi9HR*-m%M_2ofE3M{',
    'ULNmm300?^55.S%grrR5IotRNHIUt6t7%2ax',
    'UkNTzY9F_3-;~qRjM{xu_3%MM{IUD%xuWBM{',
    'UKQ9yN^M~p9vQ,$y?HNHx^I;bbxux]IoR,%N',
    'UzQvqBt6~qWBRjoft7RjtRayRjj[j[WBj[t7',
    'UgOWvn-;_39F~qofM{WB?bWBIU%M9FIUt7%M',
    'UsO|FQRP_Nt7={aeNHV@xZs:NGWBD%WBxuj[',
    'UsODnID%%M%M~qayRjof-;%MRjIUD%t7t7WB',
    'URG*]2MHS*JB*09uRis9nj%2eSt6-9t7I:Nx',
    'U{Nmi|jZXTj[~Xazn%ayIpayjEj[ROafR*kC',
    'UPL4ysNGtR-p_NoLaeR*?vWBRPM{00xuX9t7',
    'UC9k1%It00adt-oeMwWB.Tt6Dhaws=WXWAjG',
    'UYA2GRM}R%wH-pS2WAj[yZVsWXnikrozWBkC',
    'UME:PXtRIVxaT#oft7Rj9uRPV@o#nNj@WBog',
    'U6Hx+[%%GGNCL#vyI=?b00.64T#Y?800Otxw',
    'UJCP*3o}4os,_4xuD%oI-=o#RkWA?ax[NHWC',
    'UPEx,~?ZEMRj~U-:R*oJpIx[$%js-;xuRlRk',
    'UFEV7[=_NHXA00E2RiV@9atR-pxD~BsSR+S5',
    'UTG]2MkC9ut6Y7t7-;WB_NayRPofofoLe-j[',
    'UUEx^bjZj]WB~qt6WVae_3bHofRk-;WBayj[',
    'UV9bqYNHR+wI-UR*V@oLyZV?W=jYt-aeWBoK',
    'UXA^wJxuIARj.AxtRONH?cxtRPR+%ixaV?R-',
    'UCH1k+Up0P.aS_NHRT%002p+-,MSnA%0x=D-',
    'UFBgF$9v9H?a_4IrIW-o4_t8xtRj0L-.%LIU',
    'U~CvV=kDWYWARcfkazayRQWAfhoga[j=j@j]',
    'UB4N*Fr}QUMIueaPa1ixO*S0rxwPbKpZiya0',
    'UpGlV5%1IpR*_4xZRkWBT0R%oLay9bRks:j[',
    'Uv9cC;t2NYOYxbohWUW=t:kXWAWXXnWAbbj]',
    'UeJ%nrI:NFR%^,WBWCj[~EjcWEj]WVj[aza|',
    'UWJiDixsJ6sqw-s;n~ayAIn-slbH0wM|o2Wq',
    'UNI5#w,-NHs.D6IoR*ay04W9oLWA~X$gR,jY',
  ];
  $: if (!blurHash) {
    blurHash = hashes[(Math.random() * hashes.length) | 0];
  }
</script>

<BlurhashImage {fadeDuration} src={url} hash={blurHash} alt={alternativeText || caption || alt || name}/>
